"""I/O utilities for TAMBO simulation data."""

from tambo_sipm.io.hep_pulses import (
    assign_pulse_ids_from_time_gaps,
    load_hep_timeseries,
    load_segmented_hep_pulses,
    pulse_collection_to_dict,
    pulse_lengths,
    segment_hep_pulses,
)
from tambo_sipm.io.hdf5_inventory import (
    HDF5InventoryRecord,
    build_hdf5_inventory,
    inspect_hdf5_file,
    parse_test_panel_filename,
    save_hdf5_inventory,
    write_hdf5_summary,
)
from tambo_sipm.io.inventory import (
    FileInventoryRecord,
    build_data_inventory,
    inspect_csv_file,
    inspect_generic_file,
    list_files,
    save_inventory,
)
from tambo_sipm.io.loaders import (
    load_csv_table,
    load_photon_counts_csv,
    load_single_waveform_csv,
    load_waveform_collection_csv,
    require_columns,
)
from tambo_sipm.io.test_panel_hdf5 import (
    convert_test_panel_voltage,
    count_feature_valid_pulses,
    estimate_sampling_interval_ns,
    format_test_panel_voltage_unit_report,
    infer_test_panel_voltage_unit,
    load_test_panel_h5_samples,
    pulse_length_distribution,
    sampling_interval_report,
    segment_test_panel_samples,
    segment_test_panel_samples_by_threshold,
    summarize_test_panel_segmentation,
    summarize_test_panel_voltage_units,
)
from tambo_sipm.io.photon_events import (
    add_particle_metadata,
    build_photon_events,
    build_row_level_photon_events,
    detector_summary,
    filter_detector,
    load_romero_photon_table,
    particle_category_from_corsika_id,
    particle_name_from_corsika_id,
    particle_summary,
    select_detector_with_most_rows,
)

__all__ = [
    "FileInventoryRecord",
    "HDF5InventoryRecord",
    "add_particle_metadata",
    "assign_pulse_ids_from_time_gaps",
    "build_data_inventory",
    "build_hdf5_inventory",
    "build_photon_events",
    "build_row_level_photon_events",
    "convert_test_panel_voltage",
    "count_feature_valid_pulses",
    "detector_summary",
    "estimate_sampling_interval_ns",
    "filter_detector",
    "format_test_panel_voltage_unit_report",
    "infer_test_panel_voltage_unit",
    "inspect_csv_file",
    "inspect_generic_file",
    "inspect_hdf5_file",
    "list_files",
    "load_csv_table",
    "load_hep_timeseries",
    "load_photon_counts_csv",
    "load_romero_photon_table",
    "load_segmented_hep_pulses",
    "load_single_waveform_csv",
    "load_test_panel_h5_samples",
    "load_waveform_collection_csv",
    "particle_category_from_corsika_id",
    "particle_name_from_corsika_id",
    "particle_summary",
    "parse_test_panel_filename",
    "pulse_length_distribution",
    "pulse_collection_to_dict",
    "pulse_lengths",
    "require_columns",
    "save_hdf5_inventory",
    "save_inventory",
    "sampling_interval_report",
    "segment_hep_pulses",
    "segment_test_panel_samples",
    "segment_test_panel_samples_by_threshold",
    "select_detector_with_most_rows",
    "summarize_test_panel_segmentation",
    "summarize_test_panel_voltage_units",
    "write_hdf5_summary",
]
