"""Photon-event loaders for CORSIKA-derived TAMBO data.

This module handles the processed CORSIKA table produced by Antonio Romero.

For the current single-detector simulation stage, the recommended event model
is row-level:

    one row from one selected detector -> one simulated detector event

The num_fotones column is interpreted as the number of scintillation photons
generated by that row/hit.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


REQUIRED_ROMERO_COLUMNS = [
    "Detector",
    "shower",
    "num_fotones",
]

CORSIKA_PARTICLE_NAMES = {
    1: "gamma",
    2: "e+",
    3: "e-",
    5: "mu+",
    6: "mu-",
    7: "pi0",
    8: "pi+",
    9: "pi-",
    10: "K0L",
    11: "K+",
    12: "K-",
    13: "neutron",
    14: "proton",
    15: "antiproton",
    16: "K0S",
    17: "eta",
    18: "Lambda",
    19: "Sigma+",
    20: "Sigma0",
    21: "Sigma-",
    22: "Xi0",
    23: "Xi-",
    24: "Omega-",
    25: "antineutron",
    26: "anti-Lambda",
    27: "anti-Sigma-",
    28: "anti-Sigma0",
    29: "anti-Sigma+",
    30: "anti-Xi0",
    31: "anti-Xi+",
    32: "anti-Omega+",
    66: "nu_e",
    67: "anti_nu_e",
    68: "nu_mu",
    69: "anti_nu_mu",
}

ELECTROMAGNETIC_CODES = {1, 2, 3}
MUONIC_CODES = {5, 6, 68, 69, 75, 76, 85, 86, 95, 96}
HADRONIC_CODES = {
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
}


def load_romero_photon_table(path: str | Path) -> pd.DataFrame:
    """Load Antonio Romero's processed CORSIKA photon table.

    Args:
        path: CSV file path.

    Returns:
        Loaded DataFrame.

    Raises:
        FileNotFoundError: If the file does not exist.
        ValueError: If required columns are missing or photon counts are invalid.
    """
    csv_path = Path(path)

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    dataframe = pd.read_csv(csv_path)

    missing_columns = [
        column for column in REQUIRED_ROMERO_COLUMNS
        if column not in dataframe.columns
    ]

    if missing_columns:
        raise ValueError(f"Missing required columns: {missing_columns}")

    if dataframe.empty:
        raise ValueError(f"CSV file is empty: {csv_path}")

    photon_values = pd.to_numeric(dataframe["num_fotones"], errors="raise")

    if photon_values.isna().any():
        raise ValueError("num_fotones contains NaN values.")

    if (photon_values < 0).any():
        raise ValueError("num_fotones must contain non-negative values.")

    if not np.all(np.equal(photon_values, np.floor(photon_values))):
        raise ValueError("num_fotones must contain integer-valued counts.")

    dataframe = dataframe.copy()
    dataframe["num_fotones"] = photon_values.astype(np.int64)

    return dataframe


def particle_name_from_corsika_id(particle_id: int | float | None) -> str:
    """Map a CORSIKA particle ID to a particle name.

    Args:
        particle_id: CORSIKA particle identifier.

    Returns:
        Particle name or "unknown".
    """
    if particle_id is None or pd.isna(particle_id):
        return "unknown"

    return CORSIKA_PARTICLE_NAMES.get(int(particle_id), "unknown")


def particle_category_from_corsika_id(particle_id: int | float | None) -> str:
    """Map a CORSIKA particle ID to a broad particle category.

    Args:
        particle_id: CORSIKA particle identifier.

    Returns:
        One of "electromagnetic", "muonic", "hadronic", or "other".
    """
    if particle_id is None or pd.isna(particle_id):
        return "other"

    code = int(particle_id)

    if code in ELECTROMAGNETIC_CODES:
        return "electromagnetic"
    if code in MUONIC_CODES:
        return "muonic"
    if code in HADRONIC_CODES:
        return "hadronic"

    return "other"


def add_particle_metadata(
    dataframe: pd.DataFrame,
    particle_id_column: str = "id",
    particle_name_column: str = "particula",
) -> pd.DataFrame:
    """Add standardized particle metadata columns.

    Args:
        dataframe: Input photon table.
        particle_id_column: Column containing the CORSIKA particle ID.
        particle_name_column: Optional existing particle-name column.

    Returns:
        DataFrame with particle_id, particle_name and particle_category.
    """
    result = dataframe.copy()

    if particle_id_column in result.columns:
        particle_ids = pd.to_numeric(result[particle_id_column], errors="coerce")
    else:
        particle_ids = pd.Series([pd.NA] * len(result), index=result.index)

    result["particle_id"] = particle_ids.astype("Int64")

    if particle_name_column in result.columns:
        result["particle_name_original"] = result[particle_name_column].astype(str)

    mapped_names = result["particle_id"].map(particle_name_from_corsika_id)
    result["particle_name"] = mapped_names.astype(str)

    if particle_name_column in result.columns:
        result["particle_name"] = result["particle_name"].where(
            result["particle_name"] != "unknown",
            result["particle_name_original"],
        )

    result["particle_category"] = result["particle_id"].map(
        particle_category_from_corsika_id
    )

    return result


def detector_summary(
    dataframe: pd.DataFrame,
    detector_column: str = "Detector",
    shower_column: str = "shower",
    photon_column: str = "num_fotones",
) -> pd.DataFrame:
    """Summarize available data per detector.

    Args:
        dataframe: Input photon table.
        detector_column: Detector column name.
        shower_column: Shower identifier column name.
        photon_column: Photon-count column name.

    Returns:
        DataFrame with one row per detector.
    """
    required_columns = [detector_column, shower_column, photon_column]
    missing_columns = [
        column for column in required_columns if column not in dataframe.columns
    ]

    if missing_columns:
        raise ValueError(f"Missing required columns: {missing_columns}")

    summary = (
        dataframe.groupby(detector_column)
        .agg(
            rows=(photon_column, "size"),
            unique_showers=(shower_column, "nunique"),
            total_photons=(photon_column, "sum"),
            mean_photons=(photon_column, "mean"),
            median_photons=(photon_column, "median"),
            min_photons=(photon_column, "min"),
            max_photons=(photon_column, "max"),
        )
        .reset_index()
        .sort_values("rows", ascending=False)
        .reset_index(drop=True)
    )

    return summary


def particle_summary(
    dataframe: pd.DataFrame,
    photon_column: str | None = None,
) -> pd.DataFrame:
    """Summarize photon data by particle category and particle name.

    This function works both with the original Romero table, where the photon
    column is usually ``num_fotones``, and with the standardized event table,
    where the photon column is ``generated_photons``.

    Args:
        dataframe: Input photon table or standardized event table.
        photon_column: Photon-count column name. If None, it is inferred.

    Returns:
        DataFrame grouped by particle category and particle name.

    Raises:
        ValueError: If no compatible photon-count column is found.
    """
    working_dataframe = add_particle_metadata(dataframe)

    if photon_column is None:
        if "num_fotones" in working_dataframe.columns:
            photon_column = "num_fotones"
        elif "generated_photons" in working_dataframe.columns:
            photon_column = "generated_photons"
        else:
            raise ValueError(
                "Could not infer photon column. Expected 'num_fotones' "
                "or 'generated_photons'."
            )

    if photon_column not in working_dataframe.columns:
        raise ValueError(f"Missing photon column: {photon_column}")

    summary = (
        working_dataframe.groupby(["particle_category", "particle_name"])
        .agg(
            rows=(photon_column, "size"),
            total_photons=(photon_column, "sum"),
            mean_photons=(photon_column, "mean"),
            median_photons=(photon_column, "median"),
            min_photons=(photon_column, "min"),
            max_photons=(photon_column, "max"),
        )
        .reset_index()
        .sort_values("rows", ascending=False)
        .reset_index(drop=True)
    )

    return summary


def select_detector_with_most_rows(
    dataframe: pd.DataFrame,
    detector_column: str = "Detector",
) -> int | float | str:
    """Select the detector with the largest number of rows.

    Args:
        dataframe: Input photon table.
        detector_column: Detector column name.

    Returns:
        Detector identifier.
    """
    if detector_column not in dataframe.columns:
        raise ValueError(f"Missing detector column: {detector_column}")

    counts = dataframe[detector_column].value_counts(dropna=False)

    if counts.empty:
        raise ValueError("No detector values found.")

    return counts.index[0]


def filter_detector(
    dataframe: pd.DataFrame,
    detector: int | float | str,
    detector_column: str = "Detector",
) -> pd.DataFrame:
    """Filter the photon table to a single detector.

    Args:
        dataframe: Input photon table.
        detector: Detector identifier to keep.
        detector_column: Detector column name.

    Returns:
        Filtered DataFrame.

    Raises:
        ValueError: If no rows are found for the detector.
    """
    if detector_column not in dataframe.columns:
        raise ValueError(f"Missing detector column: {detector_column}")

    filtered = dataframe[dataframe[detector_column] == detector].copy()

    if filtered.empty:
        raise ValueError(f"No rows found for detector: {detector}")

    return filtered


def build_row_level_photon_events(
    dataframe: pd.DataFrame,
    detector: int | float | str | None = 0,
    detector_column: str = "Detector",
    shower_column: str = "shower",
    photon_column: str = "num_fotones",
) -> pd.DataFrame:
    """Build row-level photon events for a selected detector.

    Args:
        dataframe: Input photon table.
        detector: Detector identifier. If None, keeps all detectors.
        detector_column: Detector column name.
        shower_column: Shower identifier column name.
        photon_column: Photon-count column name.

    Returns:
        Standard event table. Each row is one simulated detector event.
    """
    required_columns = [detector_column, shower_column, photon_column]
    missing_columns = [
        column for column in required_columns if column not in dataframe.columns
    ]

    if missing_columns:
        raise ValueError(f"Missing required columns: {missing_columns}")

    working_dataframe = dataframe.copy()

    if detector is not None:
        working_dataframe = filter_detector(
            dataframe=working_dataframe,
            detector=detector,
            detector_column=detector_column,
        )

    working_dataframe = add_particle_metadata(working_dataframe)

    events = pd.DataFrame(
        {
            "event_id": [f"row_{index}" for index in working_dataframe.index],
            "source_row": working_dataframe.index.to_numpy(),
            "detector": working_dataframe[detector_column].to_numpy(),
            "shower": working_dataframe[shower_column].to_numpy(),
            "particle_id": working_dataframe["particle_id"].to_numpy(),
            "particle_name": working_dataframe["particle_name"].to_numpy(),
            "particle_category": working_dataframe[
                "particle_category"
            ].to_numpy(),
            "generated_photons": working_dataframe[photon_column].to_numpy(
                dtype=np.int64
            ),
            "n_hits": np.ones(len(working_dataframe), dtype=np.int64),
        }
    )

    if "particle_name_original" in working_dataframe.columns:
        events["particle_name_original"] = working_dataframe[
            "particle_name_original"
        ].to_numpy()

    optional_columns = [
        "t",
        "x",
        "y",
        "ek",
        "carga",
        "masa_MeV",
        "energia_detectada_poli_MeV",
        "tiempo_deteccion",
    ]

    for column in optional_columns:
        if column in working_dataframe.columns:
            events[column] = working_dataframe[column].to_numpy()

    return events.reset_index(drop=True)


def build_photon_events(
    dataframe: pd.DataFrame,
    detector: int | float | str | None = 0,
    mode: str = "row_level",
) -> pd.DataFrame:
    """Build a standard photon-event table.

    Args:
        dataframe: Input photon table.
        detector: Detector identifier. Defaults to Detector 0.
        mode: Event-building mode. Currently supported:
            - "row_level"

    Returns:
        Standard event table.

    Raises:
        ValueError: If mode is unsupported.
    """
    if mode == "row_level":
        return build_row_level_photon_events(
            dataframe=dataframe,
            detector=detector,
        )

    raise ValueError("mode must be 'row_level'.")